sudo: false

before_install:
  - pip install --quiet coveralls
  - pip install codecov

language: python

python:
  - "3.6"
node_js:
  - "8"

install:
  - pip install -r requirements/local.txt

script:
  - python manage.py makemigrations
  - coverage run manage.py test
  - coverage report

  - pylint eas

after_success:
  - coveralls

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true


