sudo: false

before_install:
  - pip install --quiet coveralls
  - pip install codecov

language: python

python:
  - "3.6"
node_js:
  - "8"

install:
  - pip install -r requirements.txt

script:
  - java -jar /opt/swagger-codegen-cli/swagger-codegen-cli.jar generate -i swagger/swagger.yaml -l javascript -o swagger/client -c swagger/codegen_options.json
  - cp .npmrc.template $HOME/.npmrc
  - npm publish

