sudo: false

before_install:
  - pip install --quiet coveralls
  - pip install codecov

language: python

python:
  - "3.6"
node_js:
  - "8"

install:
  - pip install -r requirements.txt

script:
  - cp .npmrc.template $HOME/.npmrc
  - npm publish

